[window]
opacity = 0.9

[font]
normal = { family = "IBM Plex Mono", style = "Regular" }
size = 14

[keyboard]
bindings = [
    { key = "PageUp", mods = "Control | Shift", action = "IncreaseFontSize" },
    { key = "PageDown", mods = "Control | Shift", action = "DecreaseFontSize" },

]

[colors.primary]
background = "#272822"
foreground = "#e8e8e3"

[colors.normal]
black = "#272822"
red = "#e73c50"
green = "#a6e22e"
yellow = "#e6db74"
blue = "#66d9ef"
magenta = "#ae81ff"
cyan = "#a1efe4"
white = "#e8e8e3"

[colors.bright]
black = "#64645e"
red = "#f92772"
green = "#9ec400"
yellow = "#e7c547"
blue = "#7aa6da"
magenta = "#b77ee0"
cyan = "#54ced6"
white = "#ffffff"
